#!/usr/bin/env python3
"""
build_dashboard.py — assemble a self-contained interactive HTML pharmacophore dashboard
from a data bundle produced by extract_pharmacophore_data.py.

The page is fully data-driven by the embedded DATA bundle. An optional report config
(JSON) supplies narrative/branding; anything omitted is auto-generated by the client app.

Config keys (all optional): accent, accent_dark, accent_soft, kicker, meta, summary_html,
  modes[], strategies[], interaction_map, interaction_map_note, caveat, limitations[],
  manifest, footer.

Usage:
  python3 build_dashboard.py DATA.json [--config cfg.json] [--out report.html]
      [--title "My Target — Pharmacophore Analysis"] [--accent "#4f46e5"]
"""
import argparse, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(os.path.dirname(HERE), "assets")

DEFAULTS = {
    "accent": "#4f46e5", "accent_dark": "#3730a3", "accent_soft": "#eef2ff",
    "kicker": "Structure-based pharmacophore · interactive report", "meta": "",
}

BODY = r"""
<header class="hero">
  <div class="kicker">__KICKER__</div>
  <h1 id="target-name"></h1>
  <div class="sub" id="target-sub"></div>
  <div class="tiles" id="stat-tiles"></div>
  <div class="meta-line" id="meta-line"></div>
</header>
<nav class="toc"></nav>
<main>
  <section id="overview" data-toc="Overview"><div class="card summary-card">
    <h2 class="sec"><span class="num"></span>Executive summary</h2>
    <div id="exec-summary"></div>
  </div></section>

  <section id="retention" data-toc="Retention"><div class="card">
    <h2 class="sec"><span class="num"></span>Feature retention</h2>
    <p class="sec-desc">Of all detected ligand features, how many survive the interaction filter (kept only when a complementary protein-side feature lies within the family-pair cutoff). Faded bar = all detected; solid bar = retained.</p>
    <div id="retention-chart"></div>
    <div class="verdicts" id="retention-verdicts"></div>
  </div></section>

  <section id="structures" data-toc="Structures"><div class="card">
    <h2 class="sec"><span class="num"></span>Structures &amp; 3D explorer</h2>
    <p class="sec-desc">Click any row to load its binding pocket. Ligand = cyan sticks · engaged residues = labeled sticks · retained pharmacophore features = colored spheres · H-bonds / salt bridges = dashed lines. Click headers to sort.</p>
    <table class="data-table" id="struct-table"><thead><tr>
      <th>Structure</th><th>Chemotype</th><th>Role</th><th>Category</th>
      <th class="num">Detected</th><th class="num">Retained</th><th class="num">Kept</th>
      <th class="nosort">Composition</th><th class="nosort">3D</th>
    </tr></thead><tbody></tbody></table>
    <div class="viewer-grid" style="margin-top:18px">
      <div class="viewer-wrap">
        <div class="viewer" id="viewer-main"></div>
        <div class="v-legend">
          <div class="row"><span class="sw" style="background:#22d3ee"></span>Ligand</div>
          <div class="row"><span class="v-line"></span>H-bond / salt bridge</div>
          <div class="row muted" style="margin-top:3px">spheres colored by feature family</div>
        </div>
      </div>
      <div>
        <div class="controls"><div class="fam-toggles" id="fam-toggles"></div></div>
        <div class="controls">
          <label class="ctl"><input type="checkbox" id="c-hbonds" checked>H-bonds</label>
          <label class="ctl"><input type="checkbox" id="c-labels" checked>Residue labels</label>
          <label class="ctl"><input type="checkbox" id="c-pocket" checked>Pocket</label>
          <label class="ctl"><input type="checkbox" id="c-tol">Tolerance spheres</label>
          <label class="ctl"><input type="checkbox" id="c-spin">Spin</label>
          <span class="ctl-sep"></span>
          <button class="btn" id="c-reset">Reset view</button>
        </div>
        <div class="viewer-caption" id="viewer-caption"></div>
      </div>
    </div>
    <div id="feature-detail" style="margin-top:22px"></div>
  </div></section>

  <section id="residues" data-toc="Residues"><div class="card">
    <h2 class="sec"><span class="num"></span>Receptor residue engagement</h2>
    <p class="sec-desc">Which receptor residues the retained features hydrogen-bond or salt-bridge to, across the productive structures. Bars stacked by feature family.</p>
    <div id="residue-chart"></div>
    <h3>All engaged residues</h3>
    <table class="data-table" id="residue-table"><thead><tr>
      <th>Residue</th><th class="num">Total</th><th class="num">Donor</th><th class="num">Acceptor</th><th class="num">PosIon</th><th class="nosort">Structures</th>
    </tr></thead><tbody></tbody></table>
  </div></section>

  <section id="modes-section" data-toc="Queries" style="display:none"><div class="card">
    <h2 class="sec"><span class="num"></span>Pharmacophore query recommendations</h2>
    <p class="sec-desc">Priority-ranked structure-based queries for prospective virtual screening.</p>
    <div class="mode-grid" id="mode-cards"></div>
  </div></section>

  <section id="consensus-section" data-toc="Consensus" style="display:none"><div class="card">
    <h2 class="sec"><span class="num"></span>Consensus pharmacophore query</h2>
    <p class="sec-desc">Features clustered across the aligned source structures. Present in multiple sources &rarr; mandatory; single-source &rarr; optional. Importable into Pharmer / align-it / RDKit.</p>
    <div class="tiles tiles-light" id="consensus-tiles"></div>
    <div class="viewer-grid" style="margin-top:18px">
      <div class="viewer-wrap">
        <div class="viewer" id="viewer-cons"></div>
        <div class="v-legend">
          <div class="row"><span class="sw" style="background:#22d3ee"></span>reference ligand</div>
          <div class="row muted">large sphere = mandatory · small = optional</div>
        </div>
      </div>
      <div>
        <div class="controls">
          <label class="ctl"><input type="checkbox" id="cc-mand" checked> Mandatory</label>
          <label class="ctl"><input type="checkbox" id="cc-opt" checked> Optional</label>
          <label class="ctl"><input type="checkbox" id="cc-tol">Tolerance spheres</label>
          <label class="ctl"><input type="checkbox" id="cc-spin">Spin</label>
        </div>
        <p class="sec-desc" style="margin-top:12px">Consensus features are in the aligned reference frame, overlaid on the reference ligand's pocket.</p>
        <div class="legend" id="cons-legend"></div>
      </div>
    </div>
    <div class="cons-cols">
      <div><h3>Mandatory features</h3><div id="cons-mand"></div></div>
      <div><h3>Optional features</h3><div id="cons-opt"></div></div>
    </div>
    <h3 style="margin-top:20px">Screening strategies</h3>
    <div class="strat-grid" id="strategy-cards"></div>
  </div></section>

  <section id="map" data-toc="Map"><div class="card">
    <h2 class="sec"><span class="num"></span>Global interaction map</h2>
    <pre class="imap" id="imap"></pre>
    <div class="imap-note" id="imap-note"></div>
  </div></section>

  <section id="quality" data-toc="Quality">
    <div id="caveat-block" style="margin-bottom:16px"><div class="caveat" id="caveat"></div></div>
    <details class="box"><summary>Data quality &amp; limitations</summary>
      <div class="det-body">
        <div class="lim-head"><div>Issue</div><div>Impact</div><div>Mitigation</div></div>
        <div id="limitations-body"></div>
      </div>
    </details>
  </section>

  <section id="files" data-toc="Files"><details class="box"><summary>Data manifest</summary>
    <div class="det-body"><pre class="manifest" id="manifest"></pre></div>
  </details></section>
</main>
<footer><div id="footer-note"></div></footer>
"""

TEMPLATE = r"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__PAGE_TITLE__</title>
<script src="https://cdn.jsdelivr.net/npm/3dmol@2/build/3Dmol-min.js"></script>
<script>window.addEventListener("load",function(){if(typeof $3Dmol==="undefined"){var s=document.createElement("script");s.src="https://3Dmol.org/build/3Dmol-min.js";s.onload=function(){if(window.__init3D)window.__init3D();};document.head.appendChild(s);}});</script>
<style>__STYLES__</style>
</head><body>
__BODY__
<script>
const DATA = __DATA_JSON__;
const CONFIG = __CONFIG_JSON__;
</script>
<script>__APP_JS__</script>
</body></html>
"""


def build(data, cfg, title):
    cfg = {**DEFAULTS, **(cfg or {})}
    css = (open(os.path.join(ASSETS, "styles.css")).read()
           .replace("__ACCENT__", cfg["accent"])
           .replace("__ACCENT_DARK__", cfg["accent_dark"])
           .replace("__ACCENT_SOFT__", cfg["accent_soft"]))
    appjs = open(os.path.join(ASSETS, "app.js")).read()
    body = BODY.replace("__KICKER__", cfg.get("kicker", ""))
    data_json = json.dumps(data).replace("</", "<\\/")
    config_json = json.dumps(cfg).replace("</", "<\\/")
    return (TEMPLATE.replace("__PAGE_TITLE__", title)
            .replace("__STYLES__", css).replace("__BODY__", body)
            .replace("__DATA_JSON__", data_json).replace("__CONFIG_JSON__", config_json)
            .replace("__APP_JS__", appjs))


def main():
    ap = argparse.ArgumentParser(description="Build the interactive HTML dashboard from a data bundle.")
    ap.add_argument("data", help="pharmviz_data.json from extract_pharmacophore_data.py")
    ap.add_argument("--config", help="Optional report_config.json (narrative + branding)")
    ap.add_argument("--out", default="pharmacophore_report.html")
    ap.add_argument("--title", help="HTML <title> and is otherwise derived from the target name")
    ap.add_argument("--accent", help="Accent color hex (overrides config)")
    a = ap.parse_args()
    data = json.load(open(a.data))
    cfg = json.load(open(a.config)) if a.config and os.path.isfile(a.config) else {}
    if a.accent:
        cfg["accent"] = a.accent
    title = a.title or f"{data.get('target', {}).get('name', 'Pharmacophore')} — Pharmacophore Analysis"
    html = build(data, cfg, title)
    with open(a.out, "w") as fh:
        fh.write(html)
    print(f"[build] {a.out}  ({round(len(html)/1024)} KB)")


if __name__ == "__main__":
    main()
